[build]
  # 静态网站无需构建命令
  command = ""
  # 发布目录为根目录
  publish = "."

[build.environment]
  # Node.js版本（如果需要）
  NODE_VERSION = "18"

# 重定向规则
[[redirects]]
  # 将根路径重定向到主页面
  from = "/"
  to = "/01.html"
  status = 200

[[redirects]]
  # 处理404页面，重定向到主页面
  from = "/*"
  to = "/01.html"
  status = 404

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    # 安全头部
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 缓存控制
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    # HTML文件缓存时间较短
    Cache-Control = "public, max-age=3600"

# 表单处理（如果需要）
# [build.processing]
#   skip_processing = false
# [build.processing.css]
#   bundle = true
#   minify = true
# [build.processing.js]
#   bundle = true
#   minify = true
# [build.processing.html]
#   pretty_urls = true

# 插件配置（可选）
# [[plugins]]
#   package = "netlify-plugin-minify-html"

# 环境变量（如果需要）
# [context.production.environment]
#   NODE_ENV = "production"

# [context.deploy-preview.environment]
#   NODE_ENV = "development"